# Generated by Django 2.2 on 2025-02-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
