# Generated by Django 2.2.28 on 2025-02-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20250209_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
